/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.me.sponsorvent;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import org.me.sponprof.eventlist;
import org.me.sponprof.sponprof;
import org.me.sponsor.categorysearch;
import org.me.sponsor.monthlyevent;
import org.me.sponsor.searchevent;
import org.me.sponsor.weeklyevent;

/**
 *
 * @author Shofol
 */
public class sponsorevent extends javax.swing.JFrame {

    int eventid;
    int sponid;
    Connection conn = null;
    Statement s = null;
    ResultSet r = null;
    private int pdone = 0;
    private int gdone = 0;
    private int sdone = 0;
    private int odone = 0;
    private int choice = 0;
    private String sname,pass,type;
    /**
     * Creates new form sponsorevent
     */
    public sponsorevent(int eid, int sid) {
        eventid = eid;
        sponid = sid;
        initComponents();

        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "SHOFOL", "andme420");

            String query = "Select * from FEST";

            s = conn.createStatement();
            r = s.executeQuery(query);

            while (r.next()) {
                if (eventid == r.getInt("ID")) {
                    details.setText(r.getString("SHORTDETAILS"));
                    break;
                }
            }
            String q1 = "Select * from FESTSPONTYPE";

            s = conn.createStatement();
            r = s.executeQuery(q1);

            while (r.next()) {
                if (eventid == r.getInt("FESTID") && r.getString("TYPE").equals("PLATINUM")) {
                    Object i = r.getInt("AMOUNT");
                    platinum.setText(i.toString());
                }
                if (eventid == r.getInt("FESTID") && r.getString("TYPE").equals("SILVER")) {
                    Object i = r.getInt("AMOUNT");
                    gold.setText(i.toString());
                }
                if (eventid == r.getInt("FESTID") && r.getString("TYPE").equals("GOLD")) {
                    Object i = r.getInt("AMOUNT");
                    silver.setText(i.toString());
                }
                if (eventid == r.getInt("FESTID") && r.getString("TYPE").equals("OTHER")) {
                    Object i = r.getInt("AMOUNT");
                    other.setText(i.toString());
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    public void setchoice(int c) {
        choice = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        details = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        platinum = new javax.swing.JTextField();
        gold = new javax.swing.JTextField();
        silver = new javax.swing.JTextField();
        other = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setOpaque(false);

        details.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        details.setForeground(new java.awt.Color(255, 255, 255));
        details.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Platinum");

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gold");

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Silver");

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Other");

        platinum.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        platinum.setText("N\\A");

        gold.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        gold.setText("N\\A");

        silver.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        silver.setText("N\\A");

        other.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        other.setText("N|A");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/sponsorvent/newpackage/pl.jpg"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/sponsorvent/newpackage/gold.jpg"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/sponsorvent/newpackage/silver.jpg"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/sponsorvent/newpackage/other.jpg"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("X");
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("<-");
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(567, 567, 567)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(details)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(platinum)
                            .addComponent(gold)
                            .addComponent(silver)
                            .addComponent(other, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton2))))
                .addContainerGap(290, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(268, 268, 268)
                .addComponent(details)
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(platinum))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gold, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(other, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(jLabel4))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(silver)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/sponsorvent/newpackage/Sponsor event.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String status = null;
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "SHOFOL", "andme420");

            String q3 = "SELECT * FROM FESTSPONTYPE";
            s = conn.createStatement();
            r = s.executeQuery(q3);

            while (r.next()) {
                if (r.getInt("FESTID") == eventid && r.getString("TYPE").equals("PLATINUM")) {
                    status = r.getString("STATUS");
                    break;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        if (status.equals("UNPAID")) {
            try {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "SHOFOL", "andme420");
                String q1 = "SELECT * FROM SPONSOR";

                s = conn.createStatement();
                r = s.executeQuery(q1);
                int sum = 0;
                int total = 0;

                while (r.next()) {
                    if (sponid == r.getInt("ID")) {
                        sum = r.getInt("SPENT");
                        break;
                    }
                }

                total = sum + Integer.parseInt(platinum.getText());

                String q = "UPDATE SPONSOR SET SPENT=" + total + " WHERE ID=" + sponid + "";

                s = conn.createStatement();
                s.executeQuery(q);

                String q2 = "UPDATE FESTSPONTYPE SET STATUS='PAID'";

                s = conn.createStatement();
                s.executeQuery(q2);
                int am=Integer.parseInt(platinum.getText());
                String q3 = "INSERT INTO FEST_SPONSOR (FESTID,SPONSORID,AMOUNT,TYPE)values("+eventid+","+sponid+","
                        + ""+am+",'PLATINUM')";

                s = conn.createStatement();
                s.executeQuery(q3);
                
                

                JOptionPane.showConfirmDialog(null, "Are you Sure");
            } 
            
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                e.printStackTrace();
            }
        } 
        
        else {

            JOptionPane.showMessageDialog(null, "Platinum is taken");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String status = null;
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "SHOFOL", "andme420");

            String q3 = "SELECT * FROM FESTSPONTYPE";
            s = conn.createStatement();
            r = s.executeQuery(q3);

            while (r.next()) {
                if (r.getInt("FESTID") == eventid && r.getString("TYPE").equals("GOLD")) {
                    status = r.getString("STATUS");
                    break;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        if (status.equals("UNPAID")) {
            try {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "SHOFOL", "andme420");
                String q1 = "SELECT * FROM SPONSOR";

                s = conn.createStatement();
                r = s.executeQuery(q1);
                int sum = 0;
                int total = 0;

                while (r.next()) {
                    if (sponid == r.getInt("ID")) {
                        sum = r.getInt("SPENT");
                        break;
                    }
                }

                total = sum + Integer.parseInt(platinum.getText());

                String q = "UPDATE SPONSOR SET SPENT=" + total + " WHERE ID=" + sponid + "";

                s = conn.createStatement();
                s.executeQuery(q);

                String q2 = "UPDATE FESTSPONTYPE SET STATUS='PAID'";

                s = conn.createStatement();
                s.executeQuery(q2);
                int am=Integer.parseInt(platinum.getText());
                String q3 = "INSERT INTO FEST_SPONSOR (FESTID,SPONSORID,AMOUNT,TYPE)values("+eventid+","+sponid+","
                        + ""+am+",'GOLD')";

                s = conn.createStatement();
                s.executeQuery(q3);
                
                

                JOptionPane.showConfirmDialog(null, "Are you Sure");
            } 
            
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                e.printStackTrace();
            }
        } 
        
        else {

            JOptionPane.showMessageDialog(null, "GOLD is taken");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String status = null;
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "SHOFOL", "andme420");

            String q3 = "SELECT * FROM FESTSPONTYPE";
            s = conn.createStatement();
            r = s.executeQuery(q3);

            while (r.next()) {
                if (r.getInt("FESTID") == eventid && r.getString("TYPE").equals("SILVER")) {
                    status = r.getString("STATUS");
                    break;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        if (status.equals("UNPAID")) {
            try {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "SHOFOL", "andme420");
                String q1 = "SELECT * FROM SPONSOR";

                s = conn.createStatement();
                r = s.executeQuery(q1);
                int sum = 0;
                int total = 0;

                while (r.next()) {
                    if (sponid == r.getInt("ID")) {
                        sum = r.getInt("SPENT");
                        break;
                    }
                }

                total = sum + Integer.parseInt(platinum.getText());

                String q = "UPDATE SPONSOR SET SPENT=" + total + " WHERE ID=" + sponid + "";

                s = conn.createStatement();
                s.executeQuery(q);

                String q2 = "UPDATE FESTSPONTYPE SET STATUS='PAID'";

                s = conn.createStatement();
                s.executeQuery(q2);
                int am=Integer.parseInt(platinum.getText());
                String q3 = "INSERT INTO FEST_SPONSOR (FESTID,SPONSORID,AMOUNT,TYPE)values("+eventid+","+sponid+","
                        + ""+am+",'SILVER')";

                s = conn.createStatement();
                s.executeQuery(q3);
                
                

                JOptionPane.showConfirmDialog(null, "Are you Sure");
            } 
            
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                e.printStackTrace();
            }
        } 
        
        else {

            JOptionPane.showMessageDialog(null, "Silver is taken");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String status = null;
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "SHOFOL", "andme420");

            String q3 = "SELECT * FROM FESTSPONTYPE";
            s = conn.createStatement();
            r = s.executeQuery(q3);

            while (r.next()) {
                if (r.getInt("FESTID") == eventid && r.getString("TYPE").equals("OTHER")) {
                    status = r.getString("STATUS");
                    break;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        if (status.equals("UNPAID")) {
            try {
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "SHOFOL", "andme420");
                String q1 = "SELECT * FROM SPONSOR";

                s = conn.createStatement();
                r = s.executeQuery(q1);
                int sum = 0;
                int total = 0;

                while (r.next()) {
                    if (sponid == r.getInt("ID")) {
                        sum = r.getInt("SPENT");
                        break;
                    }
                }

                total = sum + Integer.parseInt(platinum.getText());

                String q = "UPDATE SPONSOR SET SPENT=" + total + " WHERE ID=" + sponid + "";

                s = conn.createStatement();
                s.executeQuery(q);

                String q2 = "UPDATE FESTSPONTYPE SET STATUS='PAID'";

                s = conn.createStatement();
                s.executeQuery(q2);
                int am=Integer.parseInt(platinum.getText());
                String q3 = "INSERT INTO FEST_SPONSOR (FESTID,SPONSORID,AMOUNT,TYPE)values("+eventid+","+sponid+","
                        + ""+am+",'OTHER')";

                s = conn.createStatement();
                s.executeQuery(q3);
                
                

                JOptionPane.showConfirmDialog(null, "Are you Sure");
            } 
            
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                e.printStackTrace();
            }
        } 
        
        else {

            JOptionPane.showMessageDialog(null, "Other is taken");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (choice == 1) {
            searchevent a = new searchevent(sponid);
            a.setprofile(sname, pass, type);
            a.setVisible(true);
            this.dispose();
        }
       else if (choice == 2) {
            categorysearch a = new categorysearch(sponid);
            a.setprofile(sname, pass, type);
            a.setVisible(true);
            this.dispose();
        }
       else if (choice == 3) {
            weeklyevent a = new weeklyevent(sponid);
            a.setVisible(true);
            this.dispose();
        }
       else if (choice == 4) {
            monthlyevent a = new monthlyevent(sponid);
            a.setprofile(sname, pass, type);
            a.setVisible(true);
            this.dispose();
        }
       else if (choice == 5) {
            eventlist a = new eventlist(sponid);
            a.setprofile(sname, pass, type);
            a.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton6ActionPerformed
public void setprofile(String n,String p,String t){
            sname=n;
            pass=p;
            type=t;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sponsorevent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sponsorevent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sponsorevent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sponsorevent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new sponsorevent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel details;
    private javax.swing.JTextField gold;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField other;
    private javax.swing.JTextField platinum;
    private javax.swing.JTextField silver;
    // End of variables declaration//GEN-END:variables
}
